exportdemo/exportdemo/Controllers/showController.cs
using exportdemo.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace exportdemo.Controllers
{
    public class showController : Controller
    {
        public static readonly List<order> list = new List<order>
        {
            new order {OrderId ="111",Name ="ssss",Phone ="3333" },
            new order {OrderId ="112",Name ="ssss",Phone ="3333" },
            new order {OrderId ="113",Name ="ssss",Phone ="3333" },
            new order {OrderId ="114",Name ="ssss",Phone ="3333" },
            new order {OrderId ="115",Name ="ssss",Phone ="3333" }  ,
            new order {OrderId ="116",Name ="ssss",Phone ="3333" },
            new order {OrderId ="117",Name ="ssss",Phone ="3333" }

        };
        public List<order> getlist(string id )
        {
            return list.Where(i=>Convert.ToInt32( i.OrderId) >Convert.ToInt32( id)).ToList();
        }


        // GET: show
        public ActionResult Index(string id)
        {

            ViewBag.list = getlist(id);
            ViewData["list"] = getlist(id);

            return View();
        }


     
        public ActionResult ExportToExcel(   )
        {
            System.Web.HttpContext.Current.Response.Charset = "utf-8"; System.Web.HttpContext.Current.Response.ContentEncoding = System.Text.Encoding.UTF8;
            System.Web.HttpContext.Current.Response.AppendHeader("Content-Disposition", "attachment;filename=" + HttpUtility.UrlEncode("123.xls", System.Text.Encoding.UTF8).ToString());
            

            System.Web.HttpContext.Current.Response.ContentType = "application/ms-excel";
            //StringWriter tw = new StringWriter();
            System.Web.HttpContext.Current.Response.Output.Write("sdfsdfsdfsdfsdfsfsdf");
            System.Web.HttpContext.Current.Response.Flush();
            System.Web.HttpContext.Current.Response.End();
            return new EmptyResult();
        }

        [NonAction]
        protected string RenderViewToString(Controller controller, string viewName, string masterName)
        {
            IView view = ViewEngines.Engines.FindView(controller.ControllerContext, viewName, masterName).View;
            using (StringWriter writer = new StringWriter())
            {
                ViewContext viewContext = new ViewContext(controller.ControllerContext, view, controller.ViewData, controller.TempData, writer);
                viewContext.View.Render(viewContext, writer);
                return writer.ToString();
            }
        }
        [NonAction]
        protected string RenderPartialViewToString(Controller controller, string partialViewName)
        {
            IView view = ViewEngines.Engines.FindPartialView(controller.ControllerContext, partialViewName).View;
            using (StringWriter writer = new StringWriter())
            {
                ViewContext viewContext = new ViewContext(controller.ControllerContext, view, controller.ViewData, controller.TempData, writer);
                viewContext.View.Render(viewContext, writer);
                return writer.ToString();
            }
        }

        public ActionResult Export(string id)
        {

            //ViewBag.NoPaging = true;
            ViewBag.list = getlist(id);
            string viewHtml = RenderPartialViewToString(this, "Index");
            return File(System.Text.Encoding.UTF8.GetBytes(viewHtml), "application/ms-excel", string.Format("ccpi_{0}.xls", Guid.NewGuid()));
        }

    }
}

exportdemo/exportdemo/Views/show/Index.cshtml
@model  List<exportdemo.Models.order>
@{
    ViewBag.Title = "Index";
    var list = ViewBag.list; //ViewData["list"];// 
}
<style>
    tr, td {
        width: 200px;
        height: 30px;
     
    }
</style>

<h2>Index</h2>
<table id="table" border="1">
    <tbody>

        @foreach (var item in list)
            {
            <tr>
                <td>
                    <div> @item.Name </div>
                </td>
                <td>
                    <div> @item.OrderId </div>
                </td>
                <td>
                    <div> @item.Phone </div>
                </td>
            </tr>
        }

    </tbody>

</table>
@{ 
@Html.Partial("table", ViewData["list"]);


}
<input type="button" id="export" value="export" />
<a href="@Url.Action("Export", "show")?id=113" id="ttt">aaa</a>
<script src="~/Scripts/jquery-1.10.2.js">
</script>
<script type="text/javascript">

    $(document).ready(function () {

        console.log("444");
        $("#export").click(
        function () {
            console.log("ssssss");
            $.post("@Url.Action("ExportToExcel", "show")", {},function(){});
        }
        );

    });

</script>